In [1]:
import numpy as np

In [8]:
A = np.array([1,2,3])

B = np.array([[1,2,3],[4,5,6]])

print(A)

[1 2 3]


In [10]:
print(np.transpose(B))

[[1 4]
 [2 5]
 [3 6]]


In [25]:
A = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

In [30]:
np.array([A[0,2:4], A[2,2:4]])


array([[ 3,  4],
       [11, 12]])